### ISSUE TITLE
Typomvandling fungerar inte i vissa fall.

### ISSUE THREAD

**Issue by NoRines** [MelvinS4/Kandidatjobb#11]
Jag får ett segmenteringsfel när jag kör dessa rader i mandelbrot programmet.

```
47 -> var list_size;
range(ymax, ymin, -(ymax-ymin)/(float list_size)) -> var y_range;
range(xmin, xmax, (xmax-xmin)/(float list_size)) -> var x_range;
```
Dock fungerar det om jag tar bort paranteserna runt `float list_size`.

**Comment by MelvinS4** [comment]
Detta är inte ett problem med typomvandling, det är något med funktionsanrop som inte funkar. Mest troligt går något snett när man försöker parsa

``` func( ( expression) ) ```

Det har antagligen med antalet paraentesera att göra.
