### ISSUE TITLE
Makefilen måste ses över

### ISSUE THREAD

**Issue by MelvinS4** [MelvinS4/Kandidatjobb#4]
Programmet börjar ta en liten stund att kompilera, detta är något som måste ses över.

**Comment by NoRines** [comment]
Jag tycker att vi fixar detta efter en merge med master då mycket av implementationen måste flyttas till cpp filer.

**Comment by MelvinS4** [comment]
Det kan vi absolut göra, det får bli prio ett nästa cykel.

**Comment by NoRines** [comment]
Detta är löst. Stänger issue.
