### ISSUE TITLE
Kommentarer funkar inte

### ISSUE THREAD

**Issue by MelvinS4** [MelvinS4/Kandidatjobb#6]
Testade att ha en kommentar i test.majo och att skriva en i en interaktiv session, båda orsakar segmentation fault.

**Comment by NoRines** [comment]
I den interaktiv sessionen så kommer lexern retunera en tom token lista om du kommenterar ut något och detta kan inte parsern hantera. Jag får inte segmentation fault i test.majo när jag testar. Kan du ge ett exempel på när det händer?

**Comment by MelvinS4** [comment]
Detta skriver ut Unexpected char: följt av ett segfault. Detta är exakt samma fel som i den interktiva sessionen, och eftersom parsern inte har några felmeddelanden så måste det vara lexern som kraschar.

{
	for(var i in 0..100)
	{
		if(not((i/2)*2 == i and (i/3)*3 == i))
		{
			log(i);
		}
		else
			log(111111);
	}
	# lol nope ;)
	"markus är cool" -> var i;
	log(i);
}

**Comment by NoRines** [comment]
Jag får segmentation fault när skriver en kommentar i den interaktiva sessionen. Detta bör vara för att parsern inte kan hantera en tom lista med tokens. När jag testar koden du skrivit i test.majo så funkar allt som det ska.

**Comment by NoRines** [comment]
Här är lösningen i lexer.h så har en rad försvunnit.
Där det står:
```
if(*it == '#')
{
	skipComment(it, data.end());
}
```
Ska det stå:
```
if(*it == '#')
{
	skipComment(it, data.end());
	continue;
}
```
Raden följde inte med när jag pushade av någon anledning.
Stänger nu denna issue.
